import nodemailer from 'nodemailer';
import fs from 'fs/promises';
import path from 'path';

/**
 * Email notification system
 * Sends HTML emails with image thumbnails and links
 */

/**
 * Create email transporter (MSN/Outlook)
 */
export function createTransporter(emailUser, emailPassword) {
  return nodemailer.createTransporter({
    host: 'smtp-mail.outlook.com',
    port: 587,
    secure: false,
    auth: {
      user: emailUser,
      pass: emailPassword
    }
  });
}

/**
 * Generate HTML email from matches
 */
export function generateEmailHTML(matches, threshold) {
  // Separate by confidence level
  const highConfidence = matches.filter(m => m.similarity >= 85);
  const mediumConfidence = matches.filter(m => m.similarity >= threshold && m.similarity < 85);

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background: white;
      border-radius: 8px;
      padding: 30px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
      color: #2c3e50;
      margin-top: 0;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
      font-size: 1.3em;
    }
    .item {
      border: 1px solid #e1e8ed;
      border-radius: 6px;
      padding: 15px;
      margin: 15px 0;
      background: #fafafa;
      display: flex;
      gap: 20px;
    }
    .item img {
      width: 200px;
      height: 200px;
      object-fit: cover;
      border-radius: 4px;
      border: 1px solid #ddd;
    }
    .item-details {
      flex: 1;
    }
    .item-title {
      font-size: 1.1em;
      font-weight: 600;
      color: #2c3e50;
      margin: 0 0 10px 0;
    }
    .item-title a {
      color: #3498db;
      text-decoration: none;
    }
    .item-title a:hover {
      text-decoration: underline;
    }
    .item-meta {
      color: #7f8c8d;
      font-size: 0.9em;
      margin: 5px 0;
    }
    .similarity {
      display: inline-block;
      background: #3498db;
      color: white;
      padding: 3px 10px;
      border-radius: 12px;
      font-size: 0.85em;
      font-weight: 600;
      margin-bottom: 10px;
    }
    .high-confidence .similarity {
      background: #27ae60;
    }
    .matched-to {
      margin-top: 10px;
      padding: 10px;
      background: white;
      border-left: 3px solid #3498db;
      font-size: 0.9em;
    }
    .summary {
      background: #ecf0f1;
      padding: 15px;
      border-radius: 6px;
      margin: 20px 0;
    }
    .summary strong {
      color: #2c3e50;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e1e8ed;
      font-size: 0.85em;
      color: #7f8c8d;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🔔 New Similar Auctions Found!</h1>

    <div class="summary">
      <strong>Found ${matches.length} similar item${matches.length !== 1 ? 's' : ''}</strong>
      <br>
      ${highConfidence.length > 0 ? `${highConfidence.length} high confidence match${highConfidence.length !== 1 ? 'es' : ''}` : ''}
      ${mediumConfidence.length > 0 ? `${mediumConfidence.length > 0 && highConfidence.length > 0 ? ', ' : ''}${mediumConfidence.length} medium confidence match${mediumConfidence.length !== 1 ? 'es' : ''}` : ''}
    </div>

    ${highConfidence.length > 0 ? `
    <h2>✨ High Confidence Matches</h2>
    ${highConfidence.map(match => generateItemHTML(match, true)).join('')}
    ` : ''}

    ${mediumConfidence.length > 0 ? `
    <h2>🔍 Maybe Check These Too</h2>
    ${mediumConfidence.map(match => generateItemHTML(match, false)).join('')}
    ` : ''}

    <div class="footer">
      <p>This alert was generated by Auction Hound 🐕</p>
      <p>Similarity threshold: ${threshold}%</p>
    </div>
  </div>
</body>
</html>
  `;

  return html;
}

/**
 * Generate HTML for a single item
 */
function generateItemHTML(match, isHighConfidence) {
  const { newItem, matchedFavorite, similarity } = match;

  const imageUrl = newItem.images?.[0] || '';
  const title = newItem.title || 'Untitled';
  const url = newItem.url || '#';
  const endTime = newItem.endTime || 'N/A';
  const currentBid = newItem.currentBid || 'N/A';
  const estimate = newItem.estimate || 'N/A';

  return `
    <div class="item ${isHighConfidence ? 'high-confidence' : ''}">
      <img src="${imageUrl}" alt="${title}">
      <div class="item-details">
        <span class="similarity">${similarity}% Match</span>
        <div class="item-title">
          <a href="${url}" target="_blank">${title}</a>
        </div>
        <div class="item-meta">⏰ Ends: ${endTime}</div>
        <div class="item-meta">💰 Current bid: ${currentBid}</div>
        ${estimate ? `<div class="item-meta">📊 Estimate: ${estimate}</div>` : ''}
        <div class="matched-to">
          <strong>Matched to your favorite:</strong><br>
          ${matchedFavorite.title || matchedFavorite.itemId}
        </div>
      </div>
    </div>
  `;
}

/**
 * Generate plain text version
 */
export function generateEmailText(matches, threshold) {
  let text = `🔔 NEW SIMILAR AUCTIONS FOUND!\n\n`;
  text += `Found ${matches.length} similar item${matches.length !== 1 ? 's' : ''}\n`;
  text += `Threshold: ${threshold}%\n\n`;
  text += `${'='.repeat(60)}\n\n`;

  const highConfidence = matches.filter(m => m.similarity >= 85);
  const mediumConfidence = matches.filter(m => m.similarity >= threshold && m.similarity < 85);

  if (highConfidence.length > 0) {
    text += `✨ HIGH CONFIDENCE MATCHES\n\n`;
    highConfidence.forEach((match, i) => {
      text += formatMatchText(match, i + 1);
    });
  }

  if (mediumConfidence.length > 0) {
    text += `\n🔍 MAYBE CHECK THESE TOO\n\n`;
    mediumConfidence.forEach((match, i) => {
      text += formatMatchText(match, i + 1);
    });
  }

  text += `\n${'='.repeat(60)}\n`;
  text += `\nThis alert was generated by Auction Hound 🐕\n`;

  return text;
}

/**
 * Format a single match for text email
 */
function formatMatchText(match, index) {
  const { newItem, matchedFavorite, similarity } = match;

  let text = `${index}. ${newItem.title || 'Untitled'}\n`;
  text += `   Similarity: ${similarity}%\n`;
  text += `   Link: ${newItem.url}\n`;
  text += `   Ends: ${newItem.endTime || 'N/A'}\n`;
  text += `   Current bid: ${newItem.currentBid || 'N/A'}\n`;
  if (newItem.estimate) {
    text += `   Estimate: ${newItem.estimate}\n`;
  }
  text += `   Matched to: ${matchedFavorite.title || matchedFavorite.itemId}\n`;
  text += `\n`;

  return text;
}

/**
 * Send email notification
 */
export async function sendMatchEmail(transporter, toEmail, matches, threshold) {
  const htmlContent = generateEmailHTML(matches, threshold);
  const textContent = generateEmailText(matches, threshold);

  const mailOptions = {
    from: transporter.options.auth.user,
    to: toEmail,
    subject: `🔔 Found ${matches.length} Similar Auction${matches.length !== 1 ? 's' : ''}!`,
    text: textContent,
    html: htmlContent
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('✅ Email sent:', info.messageId);
    return info;
  } catch (error) {
    throw new Error(`Failed to send email: ${error.message}`);
  }
}

/**
 * Save email HTML to file (for testing without sending)
 */
export async function saveEmailPreview(matches, threshold) {
  const htmlContent = generateEmailHTML(matches, threshold);
  const previewPath = './data/email-preview.html';

  await fs.mkdir('./data', { recursive: true });
  await fs.writeFile(previewPath, htmlContent);

  console.log(`📧 Email preview saved to: ${previewPath}`);
  return previewPath;
}
